### ISSUE TITLE
French version ?

### ISSUE THREAD

**Issue by reno38** [sarbajitsaha/Batch-Uninstaller#13]
Hi Sarbajit

I just found your app on F-droid. Thank you. I'm delete apps like Flash now !
I would like to help to translate your app into French, if it's possible.
If you are interested, let me know.
I have a github account but I'm not comfortable with it (but I'm working on that).
Email : renaud.soulat@lilo.org

Thanks

**Comment by sarbajitsaha** [comment]
Hi Reno,

Thanks for your interest. Although I don't have any experience translating apps myself, I believe the process is quite straightforward. 

Basically, you need to translate the strings within the XML tags in this file https://github.com/sarbajitsaha/Batch-Uninstaller/blob/master/app/src/main/res/values/strings.xml 

So translate "Batch Uninstaller", "Don't show again" and so on. 

Once that's done, you can follow this link https://developer.android.com/guide/topics/resources/localization.html  or comment here how to add the new xml file to the project.

**Comment by sarbajitsaha** [comment]
Closed for inactivity.
