### ISSUE TITLE
It is not uninstalling app in android pie, pixel 2

### ISSUE THREAD

**Issue by shubhwicked** [sarbajitsaha/Batch-Uninstaller#16]
App is not getting uninstalled on my pixel 2 having android Pie. It is only showing toast as app uninstalled, but actually it is not.

**Comment by sarbajitsaha** [comment]
Is your phone rooted? And are you trying to uninstall a system app or user app?

**Comment by shubhwicked** [comment]
Actually, it will unistall one by one. It is working on my pixel 2.

**Comment by sejeeth11** [comment]
java.io.IOException: Cannot run program "su": error=13, Permission denied

**Comment by sarbajitsaha** [comment]
> 
> 
> java.io.IOException: Cannot run program "su": error=13, Permission denied

Hi @sejeeth11 , since you have a different issue, I would suggest you to open a new issue. The author's issue is solved, so I am closing this one.

**Comment by shubhwicked** [comment]
Hello, su is command for command line and work on rooted device.
You have to give uninstall app permission in manifest and uninstall it one
by one only, not in bulk.
