### ISSUE TITLE
Alternative download location to Playstore

### ISSUE THREAD

**Issue by IzzySoft** [sarbajitsaha/Batch-Uninstaller#3]
With the app being open source: Mind to give a download location alternative to Playstore – e.g. attaching the `.apk` to the [`releases/`](https://github.com/sarbajitsaha/Batch-Uninstaller/releases) – so folks without Playstore get a chance to give it a try?

**Comment by sarbajitsaha** [comment]
Done. APK for version 0.92 has been uploaded

**Comment by IzzySoft** [comment]
Thanks a lot! I've just [added your app to my repo](https://apt.izzysoft.de/fdroid/index/apk/com.saha.batchuninstaller) – so be welcome including a link to it so other affected users know they can use the F-Droid client to install it and keep it updated. Updates will be available usually within 24h after you created a new tag and attached the `.apk` to it.

**Comment by sarbajitsaha** [comment]
That's great. Thanks.
