### ISSUE TITLE
Adding Batch-Uninstaller to the official F-Droid Repositories

### ISSUE THREAD

**Issue by alexanderadam** [sarbajitsaha/Batch-Uninstaller#4]
It would be wonderful if Batch-Uninstaller could be added to the official [F-Droid repositories](https://f-droid.org/packages/).

AFAIK it's [a bit more complicated to have it published](https://f-droid.org/docs/FAQ_-_App_Developers/#how-do-i-get-my-app-included) but it's much better to have it in the official repositories [than having to trust another party like IzzySoft in his repository](https://github.com/sarbajitsaha/Batch-Uninstaller/issues/3).

Thank you in advance and have a nice day!

**Comment by DJCrashdummy** [comment]
finally [its issue](https://gitlab.com/fdroid/rfp/issues/196) is closed, and here it is:
https://f-droid.org/packages/com.saha.batchuninstaller/
