### ISSUE TITLE
Please update versionCode/versionName

### ISSUE THREAD

**Issue by IzzySoft** [sarbajitsaha/Batch-Uninstaller#9]
for the tags 0.91 and 0.92, you forgot to increase `versionCode` and `versionName` in your `app/build.gradle`, hence it wasn't updated in F-Droid yet (which still has 0.9). Could you please fix that? Thanks!

**Comment by sarbajitsaha** [comment]
I have updated the version code and name and created a new release. I believe that should update the app on Fdroid.
 I don't have a lot of experience with F-droid, so do let me know if anything else needs to be done to update the app there.

**Comment by IzzySoft** [comment]
I've just checked the tag – and yes, I agree that should do the trick. Let's wait for another day to see if it has been picked up (which I can check in the metadata), and another to see if it gets build. Once the update is out, this issue can be closed (feel free to ping me in about a week and check for you if you wish).

Thanks!

**Comment by sarbajitsaha** [comment]
It seems that Fdroid has updated the app to version 0.95. https://f-droid.org/packages/com.saha.batchuninstaller/

Hence, I am closing this issue.

**Comment by IzzySoft** [comment]
That's good news! I then better remove it [from my repo](https://apt.izzysoft.de/fdroid/index/apk/com.saha.batchuninstaller) (I had picked it up as F-Droid didn't update) to avoid confusion due to different signatures. Feel free to ping me should the need arise to re-establish it there :wink:
